- hosts: all

  tasks:
    - name: Install Apache.
      command: apt-get install mini-httpd 1.30-13 -y
    - name: Copy config files
      command: >
        cp httpd.conf /etc/httpd/conf/httpd.conf
      command: >
        cp httpd-vhosts.conf /etc/httpd/conf/httpd-vhosts.conf
    - name: Start Apache and configure it to run at boot.
      command: systemctl enable --now httpd
    - command: systemctl status httpd
